### ISSUE TITLE
Complete lack of documentation

### ISSUE THREAD

**Issue by DaVyper** [skyworxx/NFCLoader#1]
Nothing is explained as to where to put files, where RetroArch needs to be, how to define cards... kinda useless as is.

**Comment by DaVyper** [comment]
Thumbs down real helpful... how about showing me I'm wrong and point me to any actual instructions/setup vids/etc? They ain't here, nor on printables either, no links to it from those sites either.

I've Looked through the source the docs aren't there either, weather I launch the exe from the cmd or via gui it just closes doing nothing, no errors, no notes saying it can't find the reader or prompts for a card/cart or any response whatsoever.

**Comment by skyworxx** [comment]
The thumbs down is for the tone of your post. A little patience would go a long way.

To answer your questions. The content of mapping.txt defines the paths to emulators, cores and roms. It needs to sit in the root of the executable. The location of that executable or its relative path to Retroarch is not relevant.
